//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : SPECCPU
	/// Data Source    : SPECCPU
	/// Server Version : 3.7.17
	/// </summary>
	public partial class SPECCPUDB : LinqToDB.Data.DataConnection
	{
		public ITable<Environment> Environments { get { return this.GetTable<Environment>(); } }
		public ITable<Experiment>  Experiments  { get { return this.GetTable<Experiment>(); } }
		public ITable<Program>     Programs     { get { return this.GetTable<Program>(); } }

		public SPECCPUDB()
		{
		}

		public SPECCPUDB(string configuration)
			: base(configuration)
		{
		}
	}

	[Table("Environment")]
	public partial class Environment
	{
		[Column,     Nullable] public string CpuName  { get; set; } // text(2147483647)
		[Column,     Nullable] public string CpuMHz   { get; set; } // text(2147483647)
		[Column,     Nullable] public string FPU      { get; set; } // text(2147483647)
		[Column,     Nullable] public string Memory   { get; set; } // text(2147483647)
		[Column,     Nullable] public string OS       { get; set; } // text(2147483647)
		[Column,     Nullable] public string Compiler { get; set; } // text(2147483647)
		[PrimaryKey, Identity] public long   ID       { get; set; } // integer
	}

	[Table("Experiment")]
	public partial class Experiment
	{
		[Column,     Nullable] public decimal? BaseRunTime { get; set; } // numeric
		[Column,     Nullable] public string   url         { get; set; } // text(2147483647)
		[Column,     Nullable] public decimal? BaseRefTime { get; set; } // numeric
		[Column,     Nullable] public decimal? EnvID       { get; set; } // numeric
		[Column,     Nullable] public decimal? ProgID      { get; set; } // numeric
		[PrimaryKey, Identity] public long     ID          { get; set; } // integer
	}

	[Table("Program")]
	public partial class Program
	{
		[PrimaryKey, Identity] public long   ID   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // text(2147483647)
	}
}
